# Generated by Django 3.0.2 on 2020-01-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tacos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tortilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('size', models.IntegerField(choices=[(1, 'Pequeña'), (2, 'Mediana'), (3, 'Grande')])),
            ],
        ),
        migrations.AlterField(
            model_name='taco',
            name='tortilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tacos.Tortilla'),
        ),
    ]
